plugins:
  - jest

env:
  es2021: true
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: off
  no-console: off

overrides: [ { files: ["*.js"] } ]
